### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by apiraino** [apiraino/open-taffeta-mobile-app#5]
When the app is launched there is an error, here is the stacktrace:
```
Running Gradle task 'assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
I/flutter ( 7576): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 7576): The following assertion was thrown building BlocBuilder<ConfigurationEvent,
I/flutter ( 7576): ConfigurationState>(dirty, state: _BlocBuilderBaseState<ConfigurationEvent,
I/flutter ( 7576): ConfigurationState>#5bb3b):
I/flutter ( 7576): If neither builder nor onGenerateRoute are provided, the pageRouteBuilder must be specified so that
I/flutter ( 7576): the default handler will know what kind of PageRoute transition to build.
I/flutter ( 7576): 'package:flutter/src/widgets/app.dart': Failed assertion: line 206 pos 10: 'builder != null ||
I/flutter ( 7576):          onGenerateRoute != null ||
I/flutter ( 7576):          pageRouteBuilder != null'
I/flutter ( 7576): 
I/flutter ( 7576): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 7576): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 7576): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 7576):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 7576): 
I/flutter ( 7576): When the exception was thrown, this was the stack:
I/flutter ( 7576): #2      new WidgetsApp (package:flutter/src/widgets/app.dart:206:10)
I/flutter ( 7576): #3      _ConfigurationWrapperAppState.build.<anonymous closure> (package:flutter_door_buzzer/src/app.dart:52:18)
I/flutter ( 7576): #4      BlocBuilder.build (package:flutter_bloc/src/bloc_builder.dart:36:50)
I/flutter ( 7576): #5      _BlocBuilderBaseState.build (package:flutter_bloc/src/bloc_builder.dart:82:48)
I/flutter ( 7576): #6      StatefulElement.build (package:flutter/src/widgets/framework.dart:3825:27)
I/flutter ( 7576): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3739:15)
I/flutter ( 7576): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 7576): #9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter ( 7576): #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter ( 7576): #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter ( 7576): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 7576): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 7576): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 7576): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 7576): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter ( 7576): #17     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter ( 7576): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter ( 7576): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 7576): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 7576): #21     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:933:16)
I/flutter ( 7576): #22     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:904:5)
I/flutter ( 7576): #23     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:850:17)
I/flutter ( 7576): #24     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2258:19)
I/flutter ( 7576): #25     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:849:13)
I/flutter ( 7576): #26     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:736:7)
I/flutter ( 7576): #27     runApp (package:flutter/src/widgets/binding.dart:780:7)
I/flutter ( 7576): #28     main.run (package:flutter_door_buzzer/main.dart:13:5)
I/flutter ( 7576): #30     main.run (package:flutter_door_buzzer/main.dart:12:11)
I/flutter ( 7576): #31     main (package:flutter_door_buzzer/main.dart:18:8)
I/flutter ( 7576): #33     main (package:flutter_door_buzzer/main.dart:11:10)
I/flutter ( 7576): #34     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:199:25)
I/flutter ( 7576): #39     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:190:5)
I/flutter ( 7576): #40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:19)
I/flutter ( 7576): #41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
I/flutter ( 7576): (elided 8 frames from class _AssertionError, package dart:async, and package dart:async-patch)
I/flutter ( 7576): ════════════════════════════════════════════════════════════════════════════════════════════════════
Syncing files to device Moto G5...
I/flutter ( 7576): _ThemedApp:Closure: (BuildContext) => Widget from Function 'build':.
I/flutter ( 7576): MainPage:build
I/flutter ( 7576): HomePage:build
I/flutter ( 7576): MenuButton:build
I/flutter ( 7576): AuthenticationBloc:mapEventToState(AppStarted{})
```

**Comment by apiraino** [comment]
A bit of context: we need to find a way to display things without AppWidget, so when trying to display "intermediate" state on launch we're using kind of hacks to display things. It just says that we're not building a AppWidget correctly, but when we're moving to the "good" state it does work.

**Comment by apiraino** [comment]
I dont see this error message anymore, so I guess it was some temporarily glitch do the work-in-progress state of the source code.
